apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: msp-httpbin-operator
spec:
  schema:
    apiVersion: v1alpha1
    kind: HttpbinOperator
    spec:
      prefix: string | default="httpbin-operator"
      domain: string | default=""
      baseDomain: string | default="localhost"
      deploymentServiceType: string | default="ClusterIP"
    status:
      ocm:
        conditions:
          resourceOperator: ${resourceChart.status.conditions}
      flux:
        conditions:
          ociRepository: ${ocirepository.status.conditions}
          helmRelease: ${helmrelease.status.conditions}
  resources:
    ################################################################################
    - id: resourceChart
      template:
        apiVersion: delivery.ocm.software/v1alpha1
        kind: Resource
        metadata:
          name: "${schema.spec.prefix}-resource-chart-name"
        spec:
          componentRef:
            name: httpbin-operator-component
          resource:
            byReference:
              resource:
                name: oci-helm-chart-httpbin-operator
          additionalStatusFields:
            registry: resource.access.imageReference.toOCI().registry
            repository: resource.access.imageReference.toOCI().repository
            tag: resource.access.imageReference.toOCI().tag
          interval: 10m
          ocmConfig:
            - kind: Secret
              name: github-oci-pull-secret
    - id: ocirepository
      template:
        apiVersion: source.toolkit.fluxcd.io/v1beta2
        kind: OCIRepository
        metadata:
          name: "${schema.spec.prefix}-oci-repository-name"
        spec:
          interval: 10m
          insecure: true
          layerSelector:
            mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
            operation: copy
          url: oci://${resourceChart.status.additional.?registry}/${resourceChart.status.additional.?repository}
          ref:
            tag: ${resourceChart.status.additional.?tag}
          secretRef:
            name: github-oci-pull-secret
    - id: helmrelease
      template:
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: "${schema.spec.prefix}-helm-release-name"
        spec:
          releaseName: httpbin-operator
          interval: 10m
          timeout: 5m
          chartRef:
            kind: OCIRepository
            name: ${ocirepository.metadata.name}
            namespace: default
          install:
            crds: CreateReplace
          values:
            operator:
              args:
                - -domain=${schema.spec.domain}
                - -base-domain=${schema.spec.baseDomain}
                - -deployment-service-type=${schema.spec.deploymentServiceType}
                - -local-ingress
            imagePullSecrets:
              - name: github-oci-pull-secret
