resources:
  - ../../../config/default

patches:

  - target:
      kind: Deployment
      name: httpbin-operator-controller-manager
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: -local-ingress
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: -base-domain
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: localhost
