apiVersion: orchestrate.cloud.sap/v1alpha1
kind: HttpBinDeployment
metadata:
  labels:
    app.kubernetes.io/name: httpbin-operator
    app.kubernetes.io/managed-by: kustomize
  name: httpbindeployment-sample
spec: {}
