name: go
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - go.mod
      - go.sum
      - '**/*.go'

jobs:
  e2e:
    runs-on: ubuntu-latest
    environment: e2e-approval
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version-file: go.mod
      - name: Run e2e tests
        run: make kind-test-e2e
