name: go
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - go.mod
      - go.sum
      - '**/*.go'

jobs:
  e2e:
    runs-on: ubuntu-latest
    environment: e2e-approval
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version-file: go.mod
# TODO: uncomment and fix e2e tests
#      - name: Run e2e tests
#        run: make kind-test test-e2e
