name: OCM
on:
  push:
    tags:
      - 'ocm-*'

permissions:
  contents: read # to checkout the repository
  packages: write # to create packages

jobs:
  release:
    uses: platform-mesh/.github/.github/workflows/job-ocm.yml@main
    secrets: inherit
    with:
      chartPath: charts/example-httpbin-operator
      componentName: github.com/platform-mesh/example-httpbin-operator
      componentConstructorFile: ./component-constructor.yaml
      ocmRegistryUrl: ghcr.io/platform-mesh
