name: OCM
on:
  push:
    tags:
      - 'ocm-*'
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'ocm-config/**'
  workflow_call:
    inputs:
      chartPath:
        required: true
        type: string
      componentName:
        required: true
        type: string
      componentConstructorFile:
        required: false
        type: string
        default: ./ocm-config/component-constructor.yaml
      ocmRegistryUrl:
        type: string
        default: ghcr.io/platform-mesh

permissions:
  contents: read # to checkout the repository
  packages: write # to create packages

jobs:
  release:
    uses: platform-mesh/.github/.github/workflows/job-ocm.yml@main
    secrets: inherit
    with:
      chartPath: charts/example-httpbin-operator
      componentName: github.com/platform-mesh/example-httpbin-operator
      componentConstructorFile: ./ocm-config/component-constructor.yaml
      ocmRegistryUrl: ghcr.io/platform-mesh
