name: OCM Release
on:
  push:
    tags:
      - 'ocm-*'
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'ocm/**'
  workflow_dispatch:

env:
  #Path to the component constructor file
  componentConstructor: "./ocm/component-constructor.yaml"
  # The directory path where component artifacts (blobs) are stored.
  blobDirectory: "./ocm/ctf"

permissions:
  contents: read # to checkout the repository
  packages: write # to create packages

jobs:
  ocm:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set REGISTRY_URI from Makefile
        run: |
          REGISTRY=$(make print-registry)
          echo "REGISTRY_URI=$REGISTRY" >> $GITHUB_ENV
          echo "Parsed OCI Registry URL \"$REGISTRY\" from Makefile ..."

      - name: Set Version ENV
        run: |
          echo "VERSION=$(make print-ocm-version)" >> $GITHUB_ENV
          echo "Parsed VERSION \"$VERSION\" ..."

      - name: Login to OCI Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URI }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: setup OCM
        uses: open-component-model/ocm-setup-action@main

      - run: ocm --version

      - run: ocm add components --create --file ${{ env.blobDirectory }} ${{ env.componentConstructor }} artifactVersion=${{ env.VERSION }}

      - run: ocm transfer ctf --overwrite ${{ env.blobDirectory }} ${{ env.REGISTRY_URI }}/ocm
        if: ${{ github.event_name != 'pull_request' }}
