name: go
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - go.mod
      - go.sum
      - '**/*.go'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
        with:
          go-version-file: go.mod
      - run: make test
